### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by vanina123** [vanina123/recipe-app#13]
Hello,
We are a team of two @vanina123 and @eudondian,
Below is the link to our Kanban Board setup
https://github.com/vanina123/recipe-app/projects/1

**Comment by muneebulrehman** [comment]
Hi team, 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Provided link to the project.
- Provided info about the members.

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly give a proper title to each card. Instead of giving the title as **Student A** or **Student B**, the title should be the indicator of what the card is all about. Something like this. ⬇️
![image](https://github.com/vanina123/recipe-app/assets/33268927/2214ab5d-7591-4c00-a027-66013ad31c60)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @vanina123 and @eudondian,

✔️ Tasks are properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
